/// <reference path="./deno.d.ts" />
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_51c0d24d (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/lshqhvbasdolomemlxpe/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const supabase = createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const { error } = await supabase.from("kv_store_51c0d24d").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(`Failed to set key ${key}: ${error.message}`);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const { data, error } = await supabase.from("kv_store_51c0d24d").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(`Failed to get key ${key}: ${error.message}`);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const deleteKey = async (key: string): Promise<void> => {
  const { error } = await supabase.from("kv_store_51c0d24d").delete().eq("key", key);
  if (error) {
    throw new Error(`Failed to delete key ${key}: ${error.message}`);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const { error } = await supabase.from("kv_store_51c0d24d").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(`Failed to set multiple keys: ${error.message}`);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const { data, error } = await supabase.from("kv_store_51c0d24d").select("value").in("key", keys);
  if (error) {
    throw new Error(`Failed to get multiple keys: ${error.message}`);
  }
  return data?.map((d: { value: any }) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const { error } = await supabase.from("kv_store_51c0d24d").delete().in("key", keys);
  if (error) {
    throw new Error(`Failed to delete multiple keys: ${error.message}`);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const { data, error } = await supabase.from("kv_store_51c0d24d").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(`Failed to get keys by prefix ${prefix}: ${error.message}`);
  }
  return data?.map((d: { value: any }) => d.value) ?? [];
};

// Legacy export for backward compatibility
export const del = deleteKey;